main:
  push:
    - services:
        - docker
      stages:
        # 同名镜像构建&推送
        - name: Docker build
          script: |
            POSTGRES_VERSION=$(sed -n 's/^ARG POSTGRES_VERSION=//p' Dockerfile)
            ALPINE_VERSION=$(sed -n 's/^ARG ALPINE_VERSION=//p' Dockerfile)
            PGVECTOR_VERSION=$(sed -n 's/^ARG PGVECTOR_VERSION=//p' Dockerfile)
            IMAGE_VERSION="${POSTGRES_VERSION}-alpine${ALPINE_VERSION}-pgvector${PGVECTOR_VERSION}"
            docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${IMAGE_VERSION} -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: Docker push version
          script: |
            POSTGRES_VERSION=$(sed -n 's/^ARG POSTGRES_VERSION=//p' Dockerfile)
            ALPINE_VERSION=$(sed -n 's/^ARG ALPINE_VERSION=//p' Dockerfile)
            PGVECTOR_VERSION=$(sed -n 's/^ARG PGVECTOR_VERSION=//p' Dockerfile)
            IMAGE_VERSION="${POSTGRES_VERSION}-alpine${ALPINE_VERSION}-pgvector${PGVECTOR_VERSION}"
            docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${IMAGE_VERSION}
        - name: Docker push latest
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
        #  # 非同名镜像构建&推送
        # - name: Docker build
        #   script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/{{image-name}}:latest .
        # - name: Docker push
        #   script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/{{image-name}}:latest
